name: Deploy to EKS with Terraform

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: 'Checkout GitHub Repository'
        uses: actions/checkout@v2
    
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6 

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      - name: 'Terraform Init'
        run: terraform init

      - name: 'State Cleanup: Remove ALL K8s Resources from State'
        id: state_cleanup
        run: |
          terraform state rm 'kubernetes_secret.mysql_secret' || true
          terraform state rm 'helm_release.ingress_nginx' || true
          terraform state rm 'kubernetes_deployment.app_deployment' || true
          terraform state rm 'kubernetes_service.app_service' || true
          terraform state rm 'kubernetes_ingress_v1.app_ingress' || true
          terraform state rm 'kubernetes_horizontal_pod_autoscaler.hpa' || true
        continue-on-error: true

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
